import Head from "next/head";
import Image from "next/image";
import Login from "./Components/Login";
import { useMoralis } from "react-moralis";
export default function Home() {
  const { isAuthenticated, logout } = useMoralis();
  if (!isAuthenticated) return <Login />;
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={logout}>Logo ut</button>
    </div>
  );
}
